### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by smurthy55** [ay-lab/fithic#36]
Hi! I hope you are doing well. I am receiving this error regardless of my input file when I use an upper bound (ex. -U 120) on my data:

Traceback (most recent call last):
  File "/home/murthys3/.local/bin/fithic", line 10, in <module>
    sys.exit(main())
  File "/home/murthys3/.local/lib/python3.6/site-packages/fithic/fithic.py", line 310, in main
    (binStats,noOfFrags, maxPossibleGenomicDist, possibleIntraInRangeCount, possibleInterAllCount, interChrProb, baselineIntraChrProb)= generate_FragPairs(binStats, fragsFile, resolution)
  File "/home/murthys3/.local/lib/python3.6/site-packages/fithic/fithic.py", line 654, in generate_FragPairs
    log.write("Range of possible genomic distances  [%d  %d] \n" % (minPossibleGenomicDist, maxPossibleGenomicDist)),
OverflowError: cannot convert float infinity to integer

It seems like for the fragment file, there is an upper threshold set as infinity that cannot be converted to an integer. Do you know how I can fix this?

Thanks.

**Comment by ay-lab** [comment]
This just means you have an "infinity" or "NaN" or NA in your file where
the code is expecting an integer.

**Comment by qty9866** [comment]
I have the same question

**Comment by ay-lab** [comment]
as before, please check your file for non-integer entries in the fragment coordinates. If you can't pinpoint it, please share your fragments file
