### ISSUE TITLE
fithic crash

### ISSUE THREAD

**Issue by fgualdr** [ay-lab/fithic#46]
Hi,
I am trying to run fithic downstream of HiC-pro.
I managed to convert the Hicpro output and the iced base using the HiCPro2FitHiC utility function.
Nevertheless when running FitHiC with the produced files I get the following error which is hard for me to grasp.
Any insight is appreciated
Thanks
Francesco

Reading the contact counts file to generate bins...
Interactions file read. Time took 535.2248961925507
Traceback (most recent call last):
  File "/hpcnfs/data/GN2/fgualdrini/tools/anaconda3/envs/EnvFITHIC2/bin/fithic", line 10, in <module>
    sys.exit(main())
  File "/hpcnfs/data/GN2/fgualdrini/tools/anaconda3/envs/EnvFITHIC2/lib/python3.6/site-packages/fithic/fithic.py", line 310, in main
    (binStats,noOfFrags, maxPossibleGenomicDist, possibleIntraInRangeCount, possibleInterAllCount, interChrProb, baselineIntraChrProb)= generate_FragPairs(binStats, fragsFile, resolution)
  File "/hpcnfs/data/GN2/fgualdrini/tools/anaconda3/envs/EnvFITHIC2/lib/python3.6/site-packages/fithic/fithic.py", line 542, in generate_FragPairs
    maxFrags[ch]=max([int(i)-resolution/2 for i in allFragsDic[ch]])
ValueError: max() arg is an empty sequence

**Comment by ay-lab** [comment]
Please see issue #39
