### ISSUE TITLE
test run AttributeError

### ISSUE THREAD

**Issue by mannekim** [ay-lab/fithic#52]
Hi,

I am trying to check whether Fithic is running correctly.
When I run the run_tests-git.sh, it gives me the following error:

Traceback (most recent call last):
  File "../fithic.py", line 30, in <module>
    import matplotlib
  File "/gpfs/share/apps/anaconda3/gpu/5.2.0/envs/fithic/lib/python3.6/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import cbook, rcsetup
  File "/gpfs/share/apps/anaconda3/gpu/5.2.0/envs/fithic/lib/python3.6/site-packages/matplotlib/rcsetup.py", line 28, in <module>
    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
  File "/gpfs/share/apps/anaconda3/gpu/5.2.0/envs/fithic/lib/python3.6/site-packages/matplotlib/fontconfig_pattern.py", line 15, in <module>
    from pyparsing import (Literal, ZeroOrMore, Optional, Regex, StringEnd,
  File "/gpfs/share/apps/anaconda3/gpu/5.2.0/envs/fithic/lib/python3.6/site-packages/pyparsing/__init__.py", line 133, in <module>
    __version__ = __version_info__.__version__
AttributeError: 'version_info' object has no attribute '__version__'

A similar error appears when I run fithic using only the mandatory arguments.
I wonder if you have some ideas how to fix this?

**Comment by mannekim** [comment]
Nevermind, it was a version conflict issue which I figured out
